version: '3.1'

services:

  wordpress:
    image: "wordpress:latest"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpressdb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.node == worker01]
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.backend=wordpress"
        - "traefik.docker.network=traefik"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.frontend.rule=Host:wordpress.4labs.example"
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    volumes:
      - "wordpress:/var/www/html"
    networks:
      - traefik

  database:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.node == worker02]
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    volumes:
      - "database:/var/lib/mysql"
    networks:
      - traefik

volumes:
  wordpress:
  database:
networks:
  traefik:
    external: true
